Use custom lazy-loader for sounddevice, to get clearer error messages
When `sounddevice` is missing its PortAudio library dependency, it will
raise an error on import: `OSError: PortAudio library not found`.

However, the `lazy-loader` library imports the module in a way that
skips this import side-effect. I don't fully understand the details,
but I did observe that, if PortAudio is missing, running `pymusiclooper
play` outputs: `ERROR    module 'sounddevice' has no attribute
'OutputStream'`, suggesting it returns an empty-ish module instead of
raising an error.

In this change, we roll our own simple lazy-loader function, using
Python's built-in `importlib.import_module` function. This will raise
the more helpful error message if the PortAudio library is missing,
while still giving us the advantage of not importing the library until
we need actually need it.

I tested this change by:
1. Remove PortAudio from the system.
2. Run `pymusiclooper -i play --path <path>`.
3. See the analysis work correctly, but upon playback, `ERROR    module
   'sounddevice' has no attribute 'OutputStream'`. (This confirms both
   that we get the error, and that the module was lazy-loaded instead
   of eagerly loaded.)
4. Install PortAudio onto the system.
5. Run `pymusiclooper -i play --path <path>`.
6. See the analysis work correctly, then playback work correctly. (This
   confirms that the module loads correctly when PortAudio is present.)